# Generated by Django 4.2.4 on 2023-11-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='max_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
