# Generated by Django 4.2.4 on 2023-11-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_savingproduct_dcls_end_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproduct',
            name='max_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
