# Generated by Django 4.2.4 on 2023-11-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_savingproduct_max_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate2',
            field=models.FloatField(),
        ),
    ]
