# Generated by Django 4.2.4 on 2023-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_savingoption_intr_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=50)),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('rate_6', models.FloatField()),
                ('rate_12', models.FloatField()),
                ('rate_24', models.FloatField()),
                ('rate_36', models.FloatField()),
            ],
        ),
    ]
