# Generated by Django 4.2.4 on 2023-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_depositproductlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproductlist',
            name='rate_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproductlist',
            name='rate_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproductlist',
            name='rate_36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositproductlist',
            name='rate_6',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
