# Generated by Django 4.2.4 on 2023-11-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_depositproductlist_rate_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproductlist',
            name='fin_prdt_cd',
            field=models.CharField(max_length=50),
        ),
    ]
