# Generated by Django 4.2.4 on 2023-11-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_depositproductlist_fin_prdt_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=50)),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('rate_6', models.FloatField(blank=True, null=True)),
                ('rate_12', models.FloatField(blank=True, null=True)),
                ('rate_24', models.FloatField(blank=True, null=True)),
                ('rate_36', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
